// RobotBuilder Version: 6.1
//
// This file was generated by RobotBuilder. It contains sections of
// code that are automatically generated and assigned by robotbuilder.
// These sections will be updated in the future when you export to
// C++ from RobotBuilder. Do not put any code or make any change in
// the blocks indicating autogenerated code or it will be lost on an
// update. Deleting the comments indicating the section will prevent
// it from being updated in the future.

// ROBOTBUILDER TYPE: Subsystem.

// BEGIN AUTOGENERATED CODE, SOURCE=ROBOTBUILDER ID=INCLUDES
#include "subsystems/DriveTrain.h"
#include <frc/smartdashboard/SmartDashboard.h>

    // END AUTOGENERATED CODE, SOURCE=ROBOTBUILDER ID=INCLUDES

DriveTrain::DriveTrain(){
    SetName("Drive Train");
    // BEGIN AUTOGENERATED CODE, SOURCE=ROBOTBUILDER ID=DECLARATIONS
    SetSubsystem("Drive Train");

 AddChild("right2", &m_right2);
 m_right2.SetInverted(false);
m_right1.AddFollower(m_right2);

 AddChild("left2", &m_left2);
 m_left2.SetInverted(false);
m_left1.AddFollower(m_left2);

 AddChild("Differential Drive 1", &m_differentialDrive1);
 m_differentialDrive1.SetSafetyEnabled(true);
m_differentialDrive1.SetExpiration(0.1_s);
m_differentialDrive1.SetMaxOutput(1.0);


 AddChild("right1", &m_right1);
 m_right1.SetInverted(false);


 AddChild("left1", &m_left1);
 m_left1.SetInverted(false);


    // END AUTOGENERATED CODE, SOURCE=ROBOTBUILDER ID=DECLARATIONS
}

void DriveTrain::Periodic() {
    // Put code here to be run every loop

}

void DriveTrain::SimulationPeriodic() {
    // This method will be called once per scheduler run when in simulation

}

// BEGIN AUTOGENERATED CODE, SOURCE=ROBOTBUILDER ID=CMDPIDGETTERS

    // END AUTOGENERATED CODE, SOURCE=ROBOTBUILDER ID=CMDPIDGETTERS


// Put methods for controlling this subsystem
// here. Call these from Commands.

void DriveTrain::Drive(double left, double right) {
    m_differentialDrive1.TankDrive(left, right);
}

void DriveTrain::Stop() {
    m_differentialDrive1.TankDrive(0.0, 0.0)
}